### ISSUE TITLE
Call to function "file" failed: no file exists at policy_document.json.

### ISSUE THREAD

**Issue by farzin289** [cloudposse/terraform-aws-iam-policy-document-aggregator#14] opened 2020-03-09 12:33 UTC
I tried to made one VPC with Terraform and make module of it I tried to make policy document and use that file iam policy and attach that policy to users and groups but i face this error when i execute terraform validate
 ,could u please help me

**Comment by Nuru** [comment] 2022-06-21 18:01
Closing due to lack of information/unable to reproduce

**Closed by Nuru** 2022-06-21 18:01 UTC
Labels: invalid
